const githubResult = """ 
{
  "total_count": 7987,
  "incomplete_results": false,
  "items": [
    {
      "login": "rapha",
      "id": 29763,
      "node_id": "MDQ6VXNlcjI5NzYz",
      "avatar_url": "https://avatars0.githubusercontent.com/u/29763?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rapha",
      "html_url": "https://github.com/rapha",
      "followers_url": "https://api.github.com/users/rapha/followers",
      "following_url": "https://api.github.com/users/rapha/following{/other_user}",
      "gists_url": "https://api.github.com/users/rapha/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rapha/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rapha/subscriptions",
      "organizations_url": "https://api.github.com/users/rapha/orgs",
      "repos_url": "https://api.github.com/users/rapha/repos",
      "events_url": "https://api.github.com/users/rapha/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rapha/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphamorim",
      "id": 3630346,
      "node_id": "MDQ6VXNlcjM2MzAzNDY=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/3630346?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphamorim",
      "html_url": "https://github.com/raphamorim",
      "followers_url": "https://api.github.com/users/raphamorim/followers",
      "following_url": "https://api.github.com/users/raphamorim/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphamorim/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphamorim/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphamorim/subscriptions",
      "organizations_url": "https://api.github.com/users/raphamorim/orgs",
      "repos_url": "https://api.github.com/users/raphamorim/repos",
      "events_url": "https://api.github.com/users/raphamorim/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphamorim/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelfabeni",
      "id": 1345662,
      "node_id": "MDQ6VXNlcjEzNDU2NjI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1345662?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelfabeni",
      "html_url": "https://github.com/raphaelfabeni",
      "followers_url": "https://api.github.com/users/raphaelfabeni/followers",
      "following_url": "https://api.github.com/users/raphaelfabeni/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelfabeni/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelfabeni/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelfabeni/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelfabeni/orgs",
      "repos_url": "https://api.github.com/users/raphaelfabeni/repos",
      "events_url": "https://api.github.com/users/raphaelfabeni/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelfabeni/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelm",
      "id": 64280,
      "node_id": "MDQ6VXNlcjY0Mjgw",
      "avatar_url": "https://avatars2.githubusercontent.com/u/64280?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelm",
      "html_url": "https://github.com/raphaelm",
      "followers_url": "https://api.github.com/users/raphaelm/followers",
      "following_url": "https://api.github.com/users/raphaelm/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelm/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelm/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelm/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelm/orgs",
      "repos_url": "https://api.github.com/users/raphaelm/repos",
      "events_url": "https://api.github.com/users/raphaelm/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelm/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelbastide",
      "id": 193122,
      "node_id": "MDQ6VXNlcjE5MzEyMg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/193122?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelbastide",
      "html_url": "https://github.com/raphaelbastide",
      "followers_url": "https://api.github.com/users/raphaelbastide/followers",
      "following_url": "https://api.github.com/users/raphaelbastide/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelbastide/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelbastide/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelbastide/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelbastide/orgs",
      "repos_url": "https://api.github.com/users/raphaelbastide/repos",
      "events_url": "https://api.github.com/users/raphaelbastide/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelbastide/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "compiaffe",
      "id": 411223,
      "node_id": "MDQ6VXNlcjQxMTIyMw==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/411223?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/compiaffe",
      "html_url": "https://github.com/compiaffe",
      "followers_url": "https://api.github.com/users/compiaffe/followers",
      "following_url": "https://api.github.com/users/compiaffe/following{/other_user}",
      "gists_url": "https://api.github.com/users/compiaffe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/compiaffe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/compiaffe/subscriptions",
      "organizations_url": "https://api.github.com/users/compiaffe/orgs",
      "repos_url": "https://api.github.com/users/compiaffe/repos",
      "events_url": "https://api.github.com/users/compiaffe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/compiaffe/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaklaus",
      "id": 901936,
      "node_id": "MDQ6VXNlcjkwMTkzNg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/901936?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaklaus",
      "html_url": "https://github.com/raphaklaus",
      "followers_url": "https://api.github.com/users/raphaklaus/followers",
      "following_url": "https://api.github.com/users/raphaklaus/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaklaus/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaklaus/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaklaus/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaklaus/orgs",
      "repos_url": "https://api.github.com/users/raphaklaus/repos",
      "events_url": "https://api.github.com/users/raphaklaus/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaklaus/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelcosta",
      "id": 171371,
      "node_id": "MDQ6VXNlcjE3MTM3MQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/171371?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelcosta",
      "html_url": "https://github.com/raphaelcosta",
      "followers_url": "https://api.github.com/users/raphaelcosta/followers",
      "following_url": "https://api.github.com/users/raphaelcosta/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelcosta/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelcosta/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelcosta/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelcosta/orgs",
      "repos_url": "https://api.github.com/users/raphaelcosta/repos",
      "events_url": "https://api.github.com/users/raphaelcosta/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelcosta/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaeldealmeida",
      "id": 235028,
      "node_id": "MDQ6VXNlcjIzNTAyOA==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/235028?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaeldealmeida",
      "html_url": "https://github.com/raphaeldealmeida",
      "followers_url": "https://api.github.com/users/raphaeldealmeida/followers",
      "following_url": "https://api.github.com/users/raphaeldealmeida/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaeldealmeida/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaeldealmeida/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaeldealmeida/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaeldealmeida/orgs",
      "repos_url": "https://api.github.com/users/raphaeldealmeida/repos",
      "events_url": "https://api.github.com/users/raphaeldealmeida/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaeldealmeida/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphael",
      "id": 36822,
      "node_id": "MDQ6VXNlcjM2ODIy",
      "avatar_url": "https://avatars0.githubusercontent.com/u/36822?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphael",
      "html_url": "https://github.com/raphael",
      "followers_url": "https://api.github.com/users/raphael/followers",
      "following_url": "https://api.github.com/users/raphael/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphael/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphael/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphael/subscriptions",
      "organizations_url": "https://api.github.com/users/raphael/orgs",
      "repos_url": "https://api.github.com/users/raphael/repos",
      "events_url": "https://api.github.com/users/raphael/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphael/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelgoetter",
      "id": 491029,
      "node_id": "MDQ6VXNlcjQ5MTAyOQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/491029?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelgoetter",
      "html_url": "https://github.com/raphaelgoetter",
      "followers_url": "https://api.github.com/users/raphaelgoetter/followers",
      "following_url": "https://api.github.com/users/raphaelgoetter/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelgoetter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelgoetter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelgoetter/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelgoetter/orgs",
      "repos_url": "https://api.github.com/users/raphaelgoetter/repos",
      "events_url": "https://api.github.com/users/raphaelgoetter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelgoetter/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelsc",
      "id": 1409139,
      "node_id": "MDQ6VXNlcjE0MDkxMzk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1409139?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelsc",
      "html_url": "https://github.com/raphaelsc",
      "followers_url": "https://api.github.com/users/raphaelsc/followers",
      "following_url": "https://api.github.com/users/raphaelsc/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelsc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelsc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelsc/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelsc/orgs",
      "repos_url": "https://api.github.com/users/raphaelsc/repos",
      "events_url": "https://api.github.com/users/raphaelsc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelsc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphael-proust",
      "id": 656181,
      "node_id": "MDQ6VXNlcjY1NjE4MQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/656181?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphael-proust",
      "html_url": "https://github.com/raphael-proust",
      "followers_url": "https://api.github.com/users/raphael-proust/followers",
      "following_url": "https://api.github.com/users/raphael-proust/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphael-proust/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphael-proust/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphael-proust/subscriptions",
      "organizations_url": "https://api.github.com/users/raphael-proust/orgs",
      "repos_url": "https://api.github.com/users/raphael-proust/repos",
      "events_url": "https://api.github.com/users/raphael-proust/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphael-proust/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelchang",
      "id": 5094621,
      "node_id": "MDQ6VXNlcjUwOTQ2MjE=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/5094621?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelchang",
      "html_url": "https://github.com/raphaelchang",
      "followers_url": "https://api.github.com/users/raphaelchang/followers",
      "following_url": "https://api.github.com/users/raphaelchang/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelchang/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelchang/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelchang/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelchang/orgs",
      "repos_url": "https://api.github.com/users/raphaelchang/repos",
      "events_url": "https://api.github.com/users/raphaelchang/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelchang/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Raphael7788",
      "id": 29031430,
      "node_id": "MDQ6VXNlcjI5MDMxNDMw",
      "avatar_url": "https://avatars0.githubusercontent.com/u/29031430?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Raphael7788",
      "html_url": "https://github.com/Raphael7788",
      "followers_url": "https://api.github.com/users/Raphael7788/followers",
      "following_url": "https://api.github.com/users/Raphael7788/following{/other_user}",
      "gists_url": "https://api.github.com/users/Raphael7788/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Raphael7788/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Raphael7788/subscriptions",
      "organizations_url": "https://api.github.com/users/Raphael7788/orgs",
      "repos_url": "https://api.github.com/users/Raphael7788/repos",
      "events_url": "https://api.github.com/users/Raphael7788/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Raphael7788/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelvallat",
      "id": 25703792,
      "node_id": "MDQ6VXNlcjI1NzAzNzky",
      "avatar_url": "https://avatars1.githubusercontent.com/u/25703792?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelvallat",
      "html_url": "https://github.com/raphaelvallat",
      "followers_url": "https://api.github.com/users/raphaelvallat/followers",
      "following_url": "https://api.github.com/users/raphaelvallat/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelvallat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelvallat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelvallat/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelvallat/orgs",
      "repos_url": "https://api.github.com/users/raphaelvallat/repos",
      "events_url": "https://api.github.com/users/raphaelvallat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelvallat/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelrk",
      "id": 3377845,
      "node_id": "MDQ6VXNlcjMzNzc4NDU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/3377845?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelrk",
      "html_url": "https://github.com/raphaelrk",
      "followers_url": "https://api.github.com/users/raphaelrk/followers",
      "following_url": "https://api.github.com/users/raphaelrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelrk/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelrk/orgs",
      "repos_url": "https://api.github.com/users/raphaelrk/repos",
      "events_url": "https://api.github.com/users/raphaelrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelrk/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphabarreto",
      "id": 6462941,
      "node_id": "MDQ6VXNlcjY0NjI5NDE=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/6462941?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphabarreto",
      "html_url": "https://github.com/raphabarreto",
      "followers_url": "https://api.github.com/users/raphabarreto/followers",
      "following_url": "https://api.github.com/users/raphabarreto/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphabarreto/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphabarreto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphabarreto/subscriptions",
      "organizations_url": "https://api.github.com/users/raphabarreto/orgs",
      "repos_url": "https://api.github.com/users/raphabarreto/repos",
      "events_url": "https://api.github.com/users/raphabarreto/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphabarreto/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelkieling",
      "id": 16259523,
      "node_id": "MDQ6VXNlcjE2MjU5NTIz",
      "avatar_url": "https://avatars1.githubusercontent.com/u/16259523?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelkieling",
      "html_url": "https://github.com/raphaelkieling",
      "followers_url": "https://api.github.com/users/raphaelkieling/followers",
      "following_url": "https://api.github.com/users/raphaelkieling/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelkieling/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelkieling/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelkieling/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelkieling/orgs",
      "repos_url": "https://api.github.com/users/raphaelkieling/repos",
      "events_url": "https://api.github.com/users/raphaelkieling/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelkieling/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelschaad",
      "id": 439447,
      "node_id": "MDQ6VXNlcjQzOTQ0Nw==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/439447?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelschaad",
      "html_url": "https://github.com/raphaelschaad",
      "followers_url": "https://api.github.com/users/raphaelschaad/followers",
      "following_url": "https://api.github.com/users/raphaelschaad/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelschaad/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelschaad/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelschaad/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelschaad/orgs",
      "repos_url": "https://api.github.com/users/raphaelschaad/repos",
      "events_url": "https://api.github.com/users/raphaelschaad/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelschaad/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelstolt",
      "id": 48225,
      "node_id": "MDQ6VXNlcjQ4MjI1",
      "avatar_url": "https://avatars1.githubusercontent.com/u/48225?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelstolt",
      "html_url": "https://github.com/raphaelstolt",
      "followers_url": "https://api.github.com/users/raphaelstolt/followers",
      "following_url": "https://api.github.com/users/raphaelstolt/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelstolt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelstolt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelstolt/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelstolt/orgs",
      "repos_url": "https://api.github.com/users/raphaelstolt/repos",
      "events_url": "https://api.github.com/users/raphaelstolt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelstolt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelframos",
      "id": 896599,
      "node_id": "MDQ6VXNlcjg5NjU5OQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/896599?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelframos",
      "html_url": "https://github.com/raphaelframos",
      "followers_url": "https://api.github.com/users/raphaelframos/followers",
      "following_url": "https://api.github.com/users/raphaelframos/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelframos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelframos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelframos/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelframos/orgs",
      "repos_url": "https://api.github.com/users/raphaelframos/repos",
      "events_url": "https://api.github.com/users/raphaelframos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelframos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RaphaelJ",
      "id": 1006806,
      "node_id": "MDQ6VXNlcjEwMDY4MDY=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1006806?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RaphaelJ",
      "html_url": "https://github.com/RaphaelJ",
      "followers_url": "https://api.github.com/users/RaphaelJ/followers",
      "following_url": "https://api.github.com/users/RaphaelJ/following{/other_user}",
      "gists_url": "https://api.github.com/users/RaphaelJ/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RaphaelJ/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RaphaelJ/subscriptions",
      "organizations_url": "https://api.github.com/users/RaphaelJ/orgs",
      "repos_url": "https://api.github.com/users/RaphaelJ/repos",
      "events_url": "https://api.github.com/users/RaphaelJ/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RaphaelJ/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelpor",
      "id": 8525863,
      "node_id": "MDQ6VXNlcjg1MjU4NjM=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/8525863?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelpor",
      "html_url": "https://github.com/raphaelpor",
      "followers_url": "https://api.github.com/users/raphaelpor/followers",
      "following_url": "https://api.github.com/users/raphaelpor/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelpor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelpor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelpor/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelpor/orgs",
      "repos_url": "https://api.github.com/users/raphaelpor/repos",
      "events_url": "https://api.github.com/users/raphaelpor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelpor/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RaphaelMeudec",
      "id": 12402673,
      "node_id": "MDQ6VXNlcjEyNDAyNjcz",
      "avatar_url": "https://avatars3.githubusercontent.com/u/12402673?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RaphaelMeudec",
      "html_url": "https://github.com/RaphaelMeudec",
      "followers_url": "https://api.github.com/users/RaphaelMeudec/followers",
      "following_url": "https://api.github.com/users/RaphaelMeudec/following{/other_user}",
      "gists_url": "https://api.github.com/users/RaphaelMeudec/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RaphaelMeudec/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RaphaelMeudec/subscriptions",
      "organizations_url": "https://api.github.com/users/RaphaelMeudec/orgs",
      "repos_url": "https://api.github.com/users/RaphaelMeudec/repos",
      "events_url": "https://api.github.com/users/RaphaelMeudec/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RaphaelMeudec/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelcruzeiro",
      "id": 425640,
      "node_id": "MDQ6VXNlcjQyNTY0MA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/425640?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelcruzeiro",
      "html_url": "https://github.com/raphaelcruzeiro",
      "followers_url": "https://api.github.com/users/raphaelcruzeiro/followers",
      "following_url": "https://api.github.com/users/raphaelcruzeiro/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelcruzeiro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelcruzeiro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelcruzeiro/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelcruzeiro/orgs",
      "repos_url": "https://api.github.com/users/raphaelcruzeiro/repos",
      "events_url": "https://api.github.com/users/raphaelcruzeiro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelcruzeiro/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaeldussin",
      "id": 14662821,
      "node_id": "MDQ6VXNlcjE0NjYyODIx",
      "avatar_url": "https://avatars1.githubusercontent.com/u/14662821?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaeldussin",
      "html_url": "https://github.com/raphaeldussin",
      "followers_url": "https://api.github.com/users/raphaeldussin/followers",
      "following_url": "https://api.github.com/users/raphaeldussin/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaeldussin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaeldussin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaeldussin/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaeldussin/orgs",
      "repos_url": "https://api.github.com/users/raphaeldussin/repos",
      "events_url": "https://api.github.com/users/raphaeldussin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaeldussin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelbauer",
      "id": 524072,
      "node_id": "MDQ6VXNlcjUyNDA3Mg==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/524072?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelbauer",
      "html_url": "https://github.com/raphaelbauer",
      "followers_url": "https://api.github.com/users/raphaelbauer/followers",
      "following_url": "https://api.github.com/users/raphaelbauer/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelbauer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelbauer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelbauer/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelbauer/orgs",
      "repos_url": "https://api.github.com/users/raphaelbauer/repos",
      "events_url": "https://api.github.com/users/raphaelbauer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelbauer/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelcohn",
      "id": 1307097,
      "node_id": "MDQ6VXNlcjEzMDcwOTc=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1307097?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelcohn",
      "html_url": "https://github.com/raphaelcohn",
      "followers_url": "https://api.github.com/users/raphaelcohn/followers",
      "following_url": "https://api.github.com/users/raphaelcohn/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelcohn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelcohn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelcohn/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelcohn/orgs",
      "repos_url": "https://api.github.com/users/raphaelcohn/repos",
      "events_url": "https://api.github.com/users/raphaelcohn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelcohn/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "raphaelluchini",
      "id": 484331,
      "node_id": "MDQ6VXNlcjQ4NDMzMQ==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/484331?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/raphaelluchini",
      "html_url": "https://github.com/raphaelluchini",
      "followers_url": "https://api.github.com/users/raphaelluchini/followers",
      "following_url": "https://api.github.com/users/raphaelluchini/following{/other_user}",
      "gists_url": "https://api.github.com/users/raphaelluchini/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/raphaelluchini/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/raphaelluchini/subscriptions",
      "organizations_url": "https://api.github.com/users/raphaelluchini/orgs",
      "repos_url": "https://api.github.com/users/raphaelluchini/repos",
      "events_url": "https://api.github.com/users/raphaelluchini/events{/privacy}",
      "received_events_url": "https://api.github.com/users/raphaelluchini/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";
